sudo: required
language: groovy
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: VIqsc9Y2GGsShciSnk+Ii7mi+ifxddRo1yIvHWTBuk6tt8VPQTz1yKy3kHaTKadu4eKOGeG6Pyh+kpnStRIfSyYP7TPelQu97u7WofgIPuCWkR1P6ZknoUG3SKXtbhUV866d1xTIDqrnd+4WZgQ0BBMDeereZPjIXa9uZoDPD9u3b9xKO835kKJP1i7dQnV+cIr7Mi/xGZoJT4TQGo7A3oKYENuHyQQukPhhQsTSbdvPDnvXk6s0oLWr0lpeRAmzVKDouaE6zcIByYrqTcFSpATPSKcBl9ViNjZFzy0itXu+1J45Ot7dR73ex6id3zhaN06q2bkACSTYYeZU9cJ/6g9IUg/5txlwJybtVIEEgy1rBofDxOXJ0lvMZc8uVgee7awWxg0JuVvrDre++Rg8qA9kIWBCebacDU2MlbSEQATVDMmuem7Y/O65FZu+RRXwQzKPGeH/4O+g6I21QYZytfyAZ5OI6QqTYHzIDRRmuXC5WqEdqhtLcMVqlegfCvehNE0hfzIosKpeSwnHGGWi4Z3qMlniiGHPtYLE3pKTtZf8SCOacoW2zW3I/yL03F1LdxCg24R7QmSye0nBHHM7SjuoSAbU21JaXpCzmsTv7EKO/E83Y7rjx5JQgVebrIH9fKyD8YO9J4+tqSg5Rt1CVQXjUVvNlMBM63FQEsYzQ4c=
  app: secret-money-transfer
  on:
    repo: biniama/money-transfer
